mapping = {
    ' ': ' ',
    # VOWELS
    'a': 'A',
    'e': 'E',
    'i': 'I',
    'o': 'O',
    'u': 'U',
    # CONSONANCE
    # KA
    'k' : "k+",
    'ka': 'k',
    'ke': 'ke',
    'ki': 'ki',
    'ko': 'ko',
    'ku': 'ku',
    # GA
    'g' : "g+",
    'ga': 'g',
    'ge': 'ge',
    'gi': 'gi',
    'go': 'go',
    'gu': 'gu',
    # NGA
    'ng' : "N+",
    'nga': 'N',
    'nge': 'Ne',
    'ngi': 'Ni',
    'ngo': 'No',
    'ngu': 'Nu',
    # TA
    't' : "t+",
    'ta': 't',
    'te': 'te',
    'ti': 'ti',
    'to': 'to',
    'tu': 'tu',
    # DA
    'd' : "d+",
    'da': 'd',
    'de': 'de',
    'di': 'di',
    'do': 'do',
    'du': 'du',
    # NA
    'n' : "n+",
    'na': 'n',
    'ne': 'ne',
    'ni': 'ni',
    'no': 'no',
    'nu': 'nu',
    # PA
    'p' : "p+",
    'pa': 'p',
    'pe': 'pe',
    'pi': 'pi',
    'po': 'po',
    'pu': 'pu',
    # BA
    'b' : "b+",
    'ba': 'b',
    'be': 'be',
    'bi': 'bi',
    'bo': 'bo',
    'bu': 'bu',
    # MA
    'm' : "m+",
    'ma': 'm',
    'me': 'me',
    'mi': 'mi',
    'mo': 'mo',
    'mu': 'mu',
    # YA
    'y' : "y+",
    'ya': 'y',
    'ye': 'ye',
    'yi': 'yi',
    'yo': 'yo',
    'yu': 'yu',
    # RA
    'r' : "r+",
    'ra': 'r',
    're': 're',
    'ri': 'ri',
    'ro': 'ro',
    'ru': 'ru',
    # LA
    'l' : "l+",
    'la': 'l',
    'le': 'le',
    'li': 'li',
    'lo': 'lo',
    'lu': 'lu',
    # WA
    'w' : "w+",
    'wa': 'w',
    'we': 'we',
    'wi': 'wi',
    'wo': 'wo',
    'wu': 'wu',
    # SA
    's' : "s+",
    'sa': 's',
    'se': 'se',
    'si': 'si',
    'so': 'so',
    'su': 'su',
    # HA
    'h' : "h+",
    'ha': 'h',
    'he': 'he',
    'hi': 'hi',
    'ho': 'ho',
    'hu': 'hu',
}
